<a href="https://colab.research.google.com/github/EJVergz/AIDA-LEC/blob/main/58021_CS4DataExploration_TeyvatArchons.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Dataset Exploration**

**Teyvat Archons**

$_{\text{Â©E.D.N Almaden, A.D Buenaventura, M.A Catinoy & E.J Vergara | 2022 }}$

In [ ]:
from google.colab import files
uploaded = files.upload()

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [ ]:
import io
anime = pd.read_csv(io.BytesIO(uploaded['Anime.csv']))

In [ ]:
anime_df.shape

(15278, 27)

In [ ]:
anime_df = anime.copy()
anime_df

,animeID,name,title_english,title_japanese,title_synonyms,type,source,producers,genre,studio,...,scored_by,rank,popularity,members,favorites,synopsis,background,premiered,broadcast,related
0,1,Cowboy Bebop,Cowboy Bebop,ã«ã¦ãã¼ã¤ãããã,[],TV,Original,['Bandai Visual'],"['Action', 'Adventure', 'Comedy', 'Drama', 'Sc...",['Sunrise'],...,405664.0,26.0,39.0,795733.0,43460.0,"In the year 2071, humanity has colonized sever...",When Cowboy Bebop first aired in spring of 199...,Spring 1998,Saturdays at 01:00 (JST),"{'Adaptation': [{'mal_id': 173, 'type': 'manga..."
1,5,Cowboy Bebop: Tengoku no Tobira,Cowboy Bebop: The Movie,ã«ã¦ãã¼ã¤ãããã å¤©å½ã®æ,"[""Cowboy Bebop: Knockin' on Heaven's Door""]",Movie,Original,"['Sunrise', 'Bandai Visual']","['Action', 'Drama', 'Mystery', 'Sci-Fi', 'Space']",['Bones'],...,120243.0,164.0,449.0,197791.0,776.0,"Another day, another bountyâsuch is the life o...",NaN,NaN,NaN,"{'Parent story': [{'mal_id': 1, 'type': 'anime..."
2,6,Trigun,Trigun,ãã©ã¤ã¬ã³,[],TV,Manga,['Victor Entertainment'],"['Action', 'Sci-Fi', 'Adventure', 'Comedy', 'D...",['Madhouse'],...,212537.0,255.0,146.0,408548.0,10432.0,"Vash the Stampede is the man with a $$60,000,0...",The Japanese release by Victor Entertainment h...,Spring 1998,Thursdays at 01:15 (JST),"{'Adaptation': [{'mal_id': 703, 'type': 'manga..."
3,7,Witch Hunter Robin,Witch Hunter Robin,Witch Hunter ROBIN,['WHR'],TV,Original,['Bandai Visual'],"['Action', 'Magic', 'Police', 'Supernatural', ...",['Sunrise'],...,32837.0,2371.0,1171.0,79397.0,537.0,Witches are individuals with special powers li...,NaN,Summer 2002,Tuesdays at Unknown,{}
4,8,Bouken Ou Beet,Beet the Vandel Buster,åéºçãã£ã,['Adventure King Beet'],TV,Manga,"['TV Tokyo', 'Dentsu']","['Adventure', 'Fantasy', 'Shounen', 'Supernatu...",['Toei Animation'],...,4894.0,3544.0,3704.0,11708.0,14.0,It is the dark century and the people are suff...,NaN,Fall 2004,Thursdays at 18:30 (JST),"{'Adaptation': [{'mal_id': 1348, 'type': 'mang..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15273,39195,Beastars,NaN,BEASTARS,[],TV,Manga,[],"['Slice of Life', 'Psychological', 'Drama', 'S...",[],...,0.0,NaN,14917.0,67.0,0.0,In a world populated by anthropomorphic animal...,NaN,NaN,Unknown,"{'Adaptation': [{'mal_id': 103701, 'type': 'ma..."
15274,39196,Mairimashita! Iruma-kun,NaN,é­å ¥ãã¾ããï¼å ¥éãã,[],TV,Manga,[],"['Comedy', 'Demons', 'Supernatural', 'Fantasy'...",[],...,0.0,NaN,15231.0,59.0,0.0,Suzuki Iruma has been sold to the demon by his...,NaN,NaN,Unknown,"{'Adaptation': [{'mal_id': 104241, 'type': 'ma..."
15275,39197,Karrimor Mountain Club,Karrimor Mountain Club,Karrimor Mountain Club,[],ONA,Original,[],"['Adventure', 'Slice of Life']",[],...,0.0,11624.0,15424.0,10.0,0.0,A series of animated commercials produced by K...,NaN,NaN,NaN,{}
15276,39198,Kanata no Astra,NaN,å½¼æ¹ã®ã¢ã¹ãã©,['Astra Lost in Space'],TV,Manga,[],"['Action', 'Sci-Fi', 'Shounen', 'Space']",['Lerche'],...,0.0,0.0,0.0,0.0,2.0,"The year is 2061, when space travel is now pos...",NaN,NaN,Unknown,"{'Adaptation': [{'mal_id': 98578, 'type': 'man..."
15277,39199,Katsute Kami Datta Kemono-tachi e,NaN,ãã¤ã¦ç¥ã ã£ãç£ãã¡ã¸,['To the Abandoned Sacred Beasts'],TV,Manga,[],"['Fantasy', 'Shounen']",['MAPPA'],...,0.0,0.0,0.0,9.0,1.0,"During the Civil War, the Northâdesperate to d...",NaN,NaN,Unknown,"{'Adaptation': [{'mal_id': 72117, 'type': 'man..."

In [ ]:
anime_df = anime.copy()
anime_df.head(10)

,animeID,name,title_english,title_japanese,title_synonyms,type,source,producers,genre,studio,...,scored_by,rank,popularity,members,favorites,synopsis,background,premiered,broadcast,related
0,1,Cowboy Bebop,Cowboy Bebop,ã«ã¦ãã¼ã¤ãããã,[],TV,Original,['Bandai Visual'],"['Action', 'Adventure', 'Comedy', 'Drama', 'Sc...",['Sunrise'],...,405664.0,26.0,39.0,795733.0,43460.0,"In the year 2071, humanity has colonized sever...",When Cowboy Bebop first aired in spring of 199...,Spring 1998,Saturdays at 01:00 (JST),"{'Adaptation': [{'mal_id': 173, 'type': 'manga..."
1,5,Cowboy Bebop: Tengoku no Tobira,Cowboy Bebop: The Movie,ã«ã¦ãã¼ã¤ãããã å¤©å½ã®æ,"[""Cowboy Bebop: Knockin' on Heaven's Door""]",Movie,Original,"['Sunrise', 'Bandai Visual']","['Action', 'Drama', 'Mystery', 'Sci-Fi', 'Space']",['Bones'],...,120243.0,164.0,449.0,197791.0,776.0,"Another day, another bountyâsuch is the life o...",NaN,NaN,NaN,"{'Parent story': [{'mal_id': 1, 'type': 'anime..."
2,6,Trigun,Trigun,ãã©ã¤ã¬ã³,[],TV,Manga,['Victor Entertainment'],"['Action', 'Sci-Fi', 'Adventure', 'Comedy', 'D...",['Madhouse'],...,212537.0,255.0,146.0,408548.0,10432.0,"Vash the Stampede is the man with a $$60,000,0...",The Japanese release by Victor Entertainment h...,Spring 1998,Thursdays at 01:15 (JST),"{'Adaptation': [{'mal_id': 703, 'type': 'manga..."
3,7,Witch Hunter Robin,Witch Hunter Robin,Witch Hunter ROBIN,['WHR'],TV,Original,['Bandai Visual'],"['Action', 'Magic', 'Police', 'Supernatural', ...",['Sunrise'],...,32837.0,2371.0,1171.0,79397.0,537.0,Witches are individuals with special powers li...,NaN,Summer 2002,Tuesdays at Unknown,{}
4,8,Bouken Ou Beet,Beet the Vandel Buster,åéºçãã£ã,['Adventure King Beet'],TV,Manga,"['TV Tokyo', 'Dentsu']","['Adventure', 'Fantasy', 'Shounen', 'Supernatu...",['Toei Animation'],...,4894.0,3544.0,3704.0,11708.0,14.0,It is the dark century and the people are suff...,NaN,Fall 2004,Thursdays at 18:30 (JST),"{'Adaptation': [{'mal_id': 1348, 'type': 'mang..."
5,16,Hachimitsu to Clover,Honey and Clover,ããããã¨ã¯ã­ã¼ãã¼,"['HachiKuro', 'Honey & Clover']",TV,Manga,"['Genco', 'Fuji TV', 'Shueisha']","['Comedy', 'Drama', 'Josei', 'Romance', 'Slice...",['J.C.Staff'],...,57065.0,419.0,536.0,172274.0,3752.0,"Yuuta, Takumi, and Shinobu share a six-tatami ...",Hachimitsu to Clover was the first anime to ai...,Spring 2005,Fridays at 00:35 (JST),"{'Adaptation': [{'mal_id': 1009, 'type': 'mang..."
6,17,Hungry Heart: Wild Striker,NaN,ãã³ã°ãªã¼ãã¼ã Wild Striker,[],TV,Manga,[],"['Slice of Life', 'Comedy', 'Sports', 'Shounen']",['Nippon Animation'],...,9307.0,1186.0,3124.0,17145.0,210.0,Kyosuke Kano has lived under the shadow of his...,NaN,Fall 2002,Wednesdays at Unknown,"{'Adaptation': [{'mal_id': 4147, 'type': 'mang..."
7,18,Initial D Fourth Stage,NaN,é ­æå­ãã¤ãã·ã£ã«ãD FOURTH STAGE,['Initial D 4th Stage'],TV,Manga,"['OB Planning', 'Studio Jack']","['Action', 'Cars', 'Sports', 'Drama', 'Seinen']",['A.C.G.T.'],...,42555.0,298.0,1262.0,73438.0,635.0,Takumi Fujiwara and brothers Keisuke and Ryous...,NaN,Spring 2004,Unknown,"{'Adaptation': [{'mal_id': 375, 'type': 'manga..."
8,19,Monster,Monster,ã¢ã³ã¹ã¿ã¼,[],TV,Manga,"['VAP', 'Shogakukan Productions', 'Nippon Tele...","['Drama', 'Horror', 'Mystery', 'Police', 'Psyc...",['Madhouse'],...,131233.0,49.0,156.0,394387.0,19188.0,"Dr. Kenzo Tenma, an elite neurosurgeon recentl...",NaN,Spring 2004,Wednesdays at 00:40 (JST),"{'Adaptation': [{'mal_id': 1, 'type': 'manga',..."
9,20,Naruto,Naruto,ãã«ã,['NARUTO'],TV,Manga,"['TV Tokyo', 'Aniplex', 'Shueisha']","['Action', 'Adventure', 'Comedy', 'Super Power...",['Studio Pierrot'],...,716412.0,705.0,10.0,1091313.0,39356.0,"Moments prior to Naruto Uzumaki's birth, a hug...",Naruto received numerous awards during its air...,Fall 2002,Thursdays at 19:30 (JST),"{'Adaptation': [{'mal_id': 11, 'type': 'manga'..."

In [ ]:
anime_df = anime.copy()
anime_df.tail(3)

,animeID,name,title_english,title_japanese,title_synonyms,type,source,producers,genre,studio,...,scored_by,rank,popularity,members,favorites,synopsis,background,premiered,broadcast,related
15275,39197,Karrimor Mountain Club,Karrimor Mountain Club,Karrimor Mountain Club,[],ONA,Original,[],"['Adventure', 'Slice of Life']",[],...,0.0,11624.0,15424.0,10.0,0.0,A series of animated commercials produced by K...,NaN,NaN,NaN,{}
15276,39198,Kanata no Astra,NaN,å½¼æ¹ã®ã¢ã¹ãã©,['Astra Lost in Space'],TV,Manga,[],"['Action', 'Sci-Fi', 'Shounen', 'Space']",['Lerche'],...,0.0,0.0,0.0,0.0,2.0,"The year is 2061, when space travel is now pos...",NaN,NaN,Unknown,"{'Adaptation': [{'mal_id': 98578, 'type': 'man..."
15277,39199,Katsute Kami Datta Kemono-tachi e,NaN,ãã¤ã¦ç¥ã ã£ãç£ãã¡ã¸,['To the Abandoned Sacred Beasts'],TV,Manga,[],"['Fantasy', 'Shounen']",['MAPPA'],...,0.0,0.0,0.0,9.0,1.0,"During the Civil War, the Northâdesperate to d...",NaN,NaN,Unknown,"{'Adaptation': [{'mal_id': 72117, 'type': 'man..."

In [ ]:
anime_df.dtypes

animeID              int64
 name               object
 title_english      object
 title_japanese     object
 title_synonyms     object
 type               object
 source             object
 producers          object
 genre              object
 studio             object
 episodes          float64
 status             object
 airing             object
 aired              object
 duration           object
 rating             object
 score             float64
 scored_by         float64
 rank              float64
 popularity        float64
 members           float64
 favorites         float64
 synopsis           object
 background         object
 premiered          object
 broadcast          object
 related            object
dtype: object

In [ ]:
anime_df[['animeID',' name',' title_english',' title_japanese',' title_synonyms',' type',' source',' producers',' genre',' studio']]

,animeID,name,title_english,title_japanese,title_synonyms,type,source,producers,genre,studio
0,1,Cowboy Bebop,Cowboy Bebop,ã«ã¦ãã¼ã¤ãããã,[],TV,Original,['Bandai Visual'],"['Action', 'Adventure', 'Comedy', 'Drama', 'Sc...",['Sunrise']
1,5,Cowboy Bebop: Tengoku no Tobira,Cowboy Bebop: The Movie,ã«ã¦ãã¼ã¤ãããã å¤©å½ã®æ,"[""Cowboy Bebop: Knockin' on Heaven's Door""]",Movie,Original,"['Sunrise', 'Bandai Visual']","['Action', 'Drama', 'Mystery', 'Sci-Fi', 'Space']",['Bones']
2,6,Trigun,Trigun,ãã©ã¤ã¬ã³,[],TV,Manga,['Victor Entertainment'],"['Action', 'Sci-Fi', 'Adventure', 'Comedy', 'D...",['Madhouse']
3,7,Witch Hunter Robin,Witch Hunter Robin,Witch Hunter ROBIN,['WHR'],TV,Original,['Bandai Visual'],"['Action', 'Magic', 'Police', 'Supernatural', ...",['Sunrise']
4,8,Bouken Ou Beet,Beet the Vandel Buster,åéºçãã£ã,['Adventure King Beet'],TV,Manga,"['TV Tokyo', 'Dentsu']","['Adventure', 'Fantasy', 'Shounen', 'Supernatu...",['Toei Animation']
...,...,...,...,...,...,...,...,...,...,...
15273,39195,Beastars,NaN,BEASTARS,[],TV,Manga,[],"['Slice of Life', 'Psychological', 'Drama', 'S...",[]
15274,39196,Mairimashita! Iruma-kun,NaN,é­å ¥ãã¾ããï¼å ¥éãã,[],TV,Manga,[],"['Comedy', 'Demons', 'Supernatural', 'Fantasy'...",[]
15275,39197,Karrimor Mountain Club,Karrimor Mountain Club,Karrimor Mountain Club,[],ONA,Original,[],"['Adventure', 'Slice of Life']",[]
15276,39198,Kanata no Astra,NaN,å½¼æ¹ã®ã¢ã¹ãã©,['Astra Lost in Space'],TV,Manga,[],"['Action', 'Sci-Fi', 'Shounen', 'Space']",['Lerche']
15277,39199,Katsute Kami Datta Kemono-tachi e,NaN,ãã¤ã¦ç¥ã ã£ãç£ãã¡ã¸,['To the Abandoned Sacred Beasts'],TV,Manga,[],"['Fantasy', 'Shounen']",['MAPPA']

In [ ]:
anime_df[['animeID',' name',' title_english',' title_japanese',' title_synonyms',' type',' source',' producers',' genre',' studio']]  .sort_values('animeID', ascending=False).head(10)

,animeID,name,title_english,title_japanese,title_synonyms,type,source,producers,genre,studio
15277,39199,Katsute Kami Datta Kemono-tachi e,NaN,ãã¤ã¦ç¥ã ã£ãç£ãã¡ã¸,['To the Abandoned Sacred Beasts'],TV,Manga,[],"['Fantasy', 'Shounen']",['MAPPA']
15276,39198,Kanata no Astra,NaN,å½¼æ¹ã®ã¢ã¹ãã©,['Astra Lost in Space'],TV,Manga,[],"['Action', 'Sci-Fi', 'Shounen', 'Space']",['Lerche']
15275,39197,Karrimor Mountain Club,Karrimor Mountain Club,Karrimor Mountain Club,[],ONA,Original,[],"['Adventure', 'Slice of Life']",[]
15274,39196,Mairimashita! Iruma-kun,NaN,é­å ¥ãã¾ããï¼å ¥éãã,[],TV,Manga,[],"['Comedy', 'Demons', 'Supernatural', 'Fantasy'...",[]
15273,39195,Beastars,NaN,BEASTARS,[],TV,Manga,[],"['Slice of Life', 'Psychological', 'Drama', 'S...",[]
15272,39194,Shin Chuuka Ichiban!,NaN,çã»ä¸­è¯ä¸çª!,['New Cooking Master Boy'],Unknown,Manga,[],"['Comedy', 'Shounen']","['Production I.G', 'Nihon Ad Systems']"
15271,39192,Xia Gu Zhong An Zu,NaN,å³¡è°·éæ¡ç»,['Xiagu Zhong An Zu'],ONA,Unknown,[],['Fantasy'],[]
15270,39191,Wan Jie Shen Zhu,NaN,ä¸çç¥ä¸»,['Wanjie Shenzhu'],ONA,Unknown,[],['Fantasy'],[]
15269,39190,Wang Zhe Wai Chuan,NaN,çè æ­ªä¼,['Wangzhe Wai Chuan'],ONA,Unknown,[],['Comedy'],[]
15268,39189,Te Ke Dong Ji Pian,NaN,NaN,['ç¼å¯ä¹å¬å­£ç¯'],ONA,Unknown,[],['Action'],[]

In [ ]:
anime_df.describe()

,animeID,episodes,score,scored_by,rank,popularity,members,favorites
count,15278.000000,14732.000000,14778.000000,1.527300e+04,13669.000000,15273.000000,1.527300e+04,15273.000000
mean,19002.639416,11.726378,6.284508,1.210701e+04,6917.408004,7741.991292,2.450721e+04,329.457016
std,13706.437012,49.939231,1.073349,4.692942e+04,4003.814986,4482.323035,8.223672e+04,2829.335394
min,1.000000,1.000000,1.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000
25%,5209.250000,1.000000,5.600000,4.700000e+01,3448.000000,3855.000000,2.440000e+02,0.000000
50%,18308.000000,2.000000,6.370000,4.700000e+02,6932.000000,7769.000000,1.630000e+03,2.000000
75%,33025.750000,12.000000,7.050000,3.857000e+03,10416.000000,11627.000000,1.047200e+04,23.000000
max,39199.000000,3057.000000,10.000000,1.107955e+06,13838.000000,15474.000000,1.610561e+06,120331.000000

In [ ]:
anime_df.columns

Index(['animeID', ' name', ' title_english', ' title_japanese',
       ' title_synonyms', ' type', ' source', ' producers', ' genre',
       ' studio', ' episodes', ' status', ' airing', ' aired', ' duration',
       ' rating', ' score', ' scored_by', ' rank', ' popularity', ' members',
       ' favorites', ' synopsis', ' background', ' premiered', ' broadcast',
       ' related'],
      dtype='object')

In [ ]:
anime_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15278 entries, 0 to 15277
Data columns (total 27 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   animeID          15278 non-null  int64
 1    name            15278 non-null  object
 2    title_english   6122 non-null   object
 3    title_japanese  15230 non-null  object
 4    title_synonyms  15273 non-null  object
 5    type            15273 non-null  object
 6    source          15273 non-null  object
 7    producers       15273 non-null  object
 8    genre           15273 non-null  object
 9    studio          15273 non-null  object
 10   episodes        14732 non-null  float64
 11   status          15273 non-null  object
 12   airing          15273 non-null  object
 13   aired           15273 non-null  object
 14   duration        15273 non-null  object
 15   rating          15273 non-null  object
 16   score           14778 non-null  float64
 17   scored_by       15273 non-null  float64
 18   rank            13669 non-null  float64
 19   popularity      15273 non-null  float64
 20   members         15273 non-null  float64
 21   favorites       15273 non-null  float64
 22   synopsis        14565 non-null  object
 23   background      1118 non-null   object
 24   premiered       4179 non-null   object
 25   broadcast       4402 non-null   object
 26   related         15273 non-null  object
dtypes: float64(7), int64(1), object(19)
memory usage: 3.1+ MB

In [ ]:
anime_df.count()

Series([], dtype: int64)

In [ ]:
print(anime_df.isnull().sum())

Series([], dtype: float64)

In [ ]:
list_df = anime_df.groupby()